### ISSUE TITLE
Setting Java keywords library on classpath for runrobot

### ISSUE THREAD

**Issue by aarongarrett** [cthiele42/gradle-robot#1]
If I have a custom keywords library (written in Java) for my tests, runrobot does not see it. It is in the same directory as the RF tests file, but it must not be on the classpath for runrobot. I have attempted to modify my global classpath variable, but that also does not seem to fix the problem.

**Comment by cthiele42** [comment]
custom libraries jars have to be put on gradles buildscript classpath.
I have prepared an example for that. Please have a look an that and come back if it doesn't solve your problem.

https://github.com/cthiele42/gradle-robot/tree/master/examples/javaKeywordLib

**Comment by aarongarrett** [comment]
OK. I have solved the problem (sort of) using your example (perhaps not the best way since I'm new to Gradle). My situation is that I have RF keywords that have to be defined in Java files, and I'd like to keep those source files in the same directory as my tests .txt file (src/test/acceptancetest). So I have to compile them, jar them, and then make runrobot find them in order to run the tests. I set up a "robotFramework" task for that so that it would do those things in order (I think).

This is the relevant part of my build file:

```
buildscript {
    dependencies {
        classpath fileTree(dir: 'build/libs', include: '*.jar')
    }
}
plugins {
  id "org.roboscratch.robot" version "0.1.1"
}
apply plugin: 'java'


// Unimportant stuff... I think...


task acceptanceKeywordsCompile(dependsOn: jar, type: JavaCompile) {
    destinationDir = file('build/classes/test/acceptancetest')
    classpath = fileTree(dir: 'build/libs/', include: '*.jar')
    source = fileTree(dir: 'src/test/acceptancetest', include: '**/*.java')
}
task acceptanceKeywordsJar(dependsOn: acceptanceKeywordsCompile, type: Jar) {
    baseName = 'acceptance-keywords'
    destinationDir = file('build/libs')
    from 'build/classes/test/acceptancetest'
}
task robotFramework(dependsOn: acceptanceKeywordsJar, type: org.roboscratch.gradle.RunRobot)
```

The problem I'm having now is that the first time I run `gradle robotFramework`, it fails to find the jar file the first time I run it (complaining about an import error because no module is named whatever I call my module). The jar file certainly exists, because I can see it and have looked inside to verify that it has the class files. If I immediately run the task a second time, everything works correctly with no import issues. It also fails to remove that keywords jar file when I run `gradle clean` (unable to delete file). I don't know if these issues are related. Perhaps you can show me where I've made a mistake?

**Comment by cthiele42** [comment]
What you want to achieve seems to be a valid usecase: compileing a java keyword lib and testing it using runrobot in the very same gradle build run.

But this is colliding in some way with the gradle lifecycle.
In a first phase, gradle builds a classpath for all tasks to be used in the buildscript.
In a subsequent phase, this classpath will be used to execute all tasks including javaCompile and runRobot.

The gradle daemon plays its own role in this game: The classpath for gradle tasks built on the first daemon start cannot be modified on subsequent gradle build executions using the daemon.

The 'unable to delete file' error possibly comes from a special behavior on Windows: A jar referenced by the JVM is locked and cannot be deleted.  
1. The buildscript classpath will be constructed referencing the custom library jar
2. The clean task will run and tries to delete the jar - but this is locked (under Windows)

But there is a solution - a bit dirty but possibly acceptable in your case:
There is an example again demonstrating it: https://github.com/cthiele42/gradle-robot/tree/master/examples/javaKeywordLibDev

We do not package a jar - this is not needed for custom keyword libs.
Instead of this, we put the class files on classpath. Classfiles are not locked and scanned lazy in time of class loading.
The build has to be started with the commandline option --no-daemon. The start of the robot tests will take a while because the JPython system has to be initialized with each and every build run. This way, the newly compiled classes will be accepted during the test run.

**Comment by aarongarrett** [comment]
OK. I have modified my code to use your approach. Everything works, but I still have the issue of having to run `gradle runrobot` twice in order for the robot tests to run and pass. (They fail the first time because robot can't find the keyword library, even though it's there.) That's true whether I use `--no-daemon` or not.

For completeness and to help others trying to do this sort of thing, I'm attaching a zip file with my example project that shows how this all goes together. 

[custom-widget.zip](https://github.com/cthiele42/gradle-robot/files/441312/custom-widget.zip)

In this example, I have created a custom widget that contains a square in the center (sized at half of the smallest dimension). The square is yellow (deselected), and clicking on the square (but not outside of it) causes it to toggle (selected turns it blue). It also generates a custom event that listeners can register, as in the example application where a label is updated with "SELECTED" or "NOT SELECTED" accordingly.

Feel free to do with it what you will. As far as I'm concerned, this issue is now closed to my satisfaction. Thank you for all of your help.

**Edit**: That Gradle file is missing the dependency for Junit. That block should be as follows:

```
dependencies {
    compile 'org.robotframework:swinglibrary:1.9.6'
    compile 'org.robotframework:javalib-core:1.2.1'
    testCompile 'junit:junit:4.12'
}
```

**Comment by cthiele42** [comment]
Thank you for providing the example code. I was able to reproduce the problem:
The directory _build/classes/main_ has to exist to be added to the classpath - this is not the case after a fresh project start or after a clean was running.
It can be fixed with the following change:

classpath files(mkdir('build/classes/main'))

I opened issue #2 to provide a reliable solution for the use case behind.

**Comment by aarongarrett** [comment]
Perfect! That worked as advertised. 
You had mentioned in the Gradle file comment about using properties of the java task instead of (I presume) the hard-coded directory structure. Would that be something that would still work with the mkdir thing? I suppose it would be something like `sourceSets.main.output.classesDir`. When I try it with that (with and without the mkdir), Gradle complains about that "variable" or whatever not existing. Is that because the java plugin doesn't exist until later in the script? Or do I just have no clue as to what I'm doing here?
